name: Build minimal image

on:
  [push, workflow_dispatch]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: checkout
        uses: actions/checkout@v3

      - name: set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: build and push
        uses: docker/build-push-action@v6
        with:
          context: ./standard-v4/
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/v4:latest
          platforms: linux/arm64, linux/amd64